version: "3.6"

services:
  nats-cluster-1:
    image: nats:2.8.2-alpine3.15
    container_name: nats-cluster-1
    command: ["-c", "/cluster.config"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes: 
      - "./config/nats-cluster-1.config:/cluster.config"

  nats-cluster-2:
    image: nats:2.8.2-alpine3.15
    container_name: nats-cluster-2
    command: ["-c", "cluster.config"]
    ports:
      - "4223:4222"
      - "8223:8222"
    volumes: 
      - "./config/nats-cluster-2.config:/cluster.config"

  nats-cluster-3:
    image: nats:2.8.2-alpine3.15
    container_name: nats-cluster-3
    command: ["-c", "cluster.config"]
    ports:
      - "4224:4222"
      - "8224:8222"
    volumes: 
      - "./config/nats-cluster-3.config:/cluster.config"