version: '3.4'

services:
  mysql:
    image: mysql:latest
    platform: linux/amd64
    container_name: "mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "0"
      MYSQL_DATABASE: "trading"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    networks: 
      - network-trading
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          memory: 2G

  tradingserver:
    image: tradingserver:latest
    container_name: "trading-server"
    restart: always
    ports:
      - 6600:6600
    networks:
      - network-trading
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          memory: 2G
    depends_on:
      mysql:
        condition: "service_started"

networks:
    network-trading:
      driver: bridge