FROM golang:1.21 AS builder
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
ENV GO111MODULE=on 
RUN mkdir -p /app
WORKDIR /app
COPY go.mod . 
COPY go.sum .
RUN go mod download
COPY . .
RUN go build -ldflags "-s -w" -o tinderserver

FROM centos:centos7
RUN mkdir -p /app
COPY --from=builder /app/tinderserver /app/tinderserver
WORKDIR /app
COPY /config/env.yaml.template ./env.yaml
CMD ["./tinderserver", "-f", "./env.yaml", "server"]